### ISSUE TITLE
Fog isn't being reset when no fog card is picked

### ISSUE THREAD

**Issue by Derpduck** [MrFailzz/Swarm-Mode#47]
![20231006075731_1](https://github.com/MrFailzz/Swarm-Mode/assets/934223/ca2121f1-7ce2-42b3-a129-0be686e9f573)

**Comment by MrFailzz** [comment]
It technically is resetting but it goes to a specific value rather than the map default. I tried saving the default fog values for the map but couldn't ever get the color to reset properly (specifically for the skybox I think).

https://github.com/MrFailzz/Swarm-Mode/blob/main/scripts/vscripts/swarm/swarm_globals.nut#L20-L31
https://github.com/MrFailzz/Swarm-Mode/blob/main/scripts/vscripts/swarm/swarm_corruption.nut#L336-L342

**Comment by Derpduck** [comment]
I think this might be the correct method, the way colors are stored is really odd https://github.com/MrFailzz/Swarm-Mode/blob/main/scripts/vscripts/swarm/swarm_hazards.nut#L444
Also I think some maps can have more than 1 fog controller which might make things more complicated

**Comment by Derpduck** [comment]
Can't get this to work properly yet
https://github.com/MrFailzz/Swarm-Mode/commit/45f1756717a2c6d9bcf0a84b02223bc42e7e4e7f
